### Проверка с использованием exception (xcheck)

Верный output – еще не гарантия хорошего решения, особенно, если у нас есть специальные требования к типам, названиями переменных или содержанию внутрених объектов.

Если задание не должно засчитаться, несмотря на верный output, можно ронять выполнение кода через exception.

    if <неверное условие>:
        raise Exception(<сообщение об ошибке>)
    
Если таких условий много, удобно структурироваться и использовать функцию

    def xcheck(value,clue,message): 
        if value != clue:
            raise Exception(message)

#### Пример:

Предположим, нам важно, чтобы учащийся принимал данные в словарь, а не в список или скаляр.

Для этого мы будем ронять выполнение кода 

    if type(d) != dict":
        raise Exception("Объект d должен быть словарем!")
        
        
Или, используя функцию:

    xcheck(type(d), dict, "Объект d должен быть словарем!")
    
Добавим еще несколько примеров

    xcheck(type(d), dict, "Объект d должен быть словарем!")
    xcheck(len(d), 7, "В словаре должно быть 4 элемента")      
    xcheck(d.get("а"), 7, "В словаре d по ключу a должно храниться значение 7")
  
   